from medspacy.ner import TargetRule

psh_target_rules = [
        # TargetRule("suicide", "PROBLEM", pattern=r"\bsuicid(e|al)(ity)?\b"),
        # TargetRule("suicide", "PROBLEM", pattern=r"\boverdose\b"),
        # TargetRule("suicide", "PROBLEM", pattern=r"\b(kill|hurt).{0,5}self\b"),
        # TargetRule("suicide", "PROBLEM", pattern=r"\bself(-|\s)(injury|harm|destructive)\b"),

        TargetRule("history of suicide", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "((h/o)|hx|history|prev|previous|past|earlier|past|prior|report(s|ed)?)"}},
                       {"LOWER": "(of|intermittent)", "OP": "?"},
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                   ]),
        TargetRule("history of chronic suicide", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(hx|history|prev|previous|past|earlier|past|prior|report(s|ed)?)"}},
                       {"LOWER": "of", "OP": "?"},
                       {"LOWER": "(intermittent|chronic|attempted|multiple|single|one|two|three)", "OP": "?"},
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                   ]),
        TargetRule("suicide history", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                       {"LOWER": {"REGEX": "((h/o)|hx|history|prev|previous|past|earlier|prior|report(s|ed)?)"}},
                   ]),
        TargetRule("suicide in <YEAR>", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("suicide attempt in <YEAR>", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "suicid(e|al)"}},
                       {"LOWER": "attempt", "OP": "?"},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("suicide attempt in <YEAR>", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                       {"LOWER": {"REGEX": "attempt"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("self-harm history", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "self\-?(harm|injury|hurt|kill|destructive)"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|prior|report(s|ed)?)"}},
                   ]),
        TargetRule("history of self-harm", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|prior|report(s|ed)?)"}},
                       {"LOWER": "of", "OP": "?"},
                       {"LOWER": {"REGEX": "self\-?(harm|injury|hurt|kill|destructive)"}},
                   ]),
        TargetRule("self-harm in <YEAR>", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "self\-?(harm|injury|hurt|kill|destructive)"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("history of overdose", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|prior|report(s|ed)?)"}},
                       {"LOWER": "of", "OP": "?"},
                       {"LOWER": {"REGEX": "overdose"}},
                   ]),
        TargetRule("overdose history", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "overdose"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|prior|report(s|ed)?)"}},
                   ]),
        TargetRule("overdose in <YEAR>", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "overdose"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("commit suicide", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "commit(ed)?|attempt(ed)?|tried|experienced|felt"}},
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                   ]),
        TargetRule("suicide in the past", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": "the", "OP": "?"},
                       {"LOWER": {"REGEX": "past|prior|before|earlier|prev|previous(ly)?"}},
                   ]),
        TargetRule("past suicide", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "past|prior|before|last|earlier|prev|previous(ly)?"}},
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                   ]),
        TargetRule("suicide attempt in <YEAR>", "SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(suicid(e|al)(ity)?|SI|SA|SB)"}},
                       {"LOWER": "attempt", "OP": "?"},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
    ]

fsh_target_rules = [
        TargetRule("family died by suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "(commit(ted)?|completed|(un)?successful|died|SA|death|kill(ed)?)"}},
                       {"LOWER": {"REGEX": "(of|by|from)"}, "OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("family with completed suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "(commit(ted)?|complete(d)?|(un)?successful)"}, "OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("family history of suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "((h/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": {"REGEX": "of"}, "OP": "?"},
                       {"LOWER": {"REGEX": "(completed|committed)"}, "OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("family suicide history", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                       {"LOWER": {"REGEX": "((h/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                   ]),
        TargetRule("family suicide in <YEAR>", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("family suicide attempt in <YEAR>", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                       {"LOWER": {"REGEX": "attempt"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "^[\d]{4}$"}},
                   ]),
        TargetRule("family self-harm history", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "self\-?(harm|injury|hurt|kill|destructive)"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                   ]),
        TargetRule("family history of self-harm", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": "of", "OP": "?"},
                       {"LOWER": {"REGEX": "self\-?(harm|injury|hurt|kill|destructive)"}},
                   ]),
        TargetRule("self-harm history in family", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "self\-?(harm|injury|hurt|kill|destructive)"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                   ]),
        TargetRule("family history of overdose", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": "of", "OP": "?"},
                       {"LOWER": {"REGEX": "overdose"}},
                   ]),
        TargetRule("overdose history in family", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "overdose"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": "in", "OP": "?"},
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                   ]),
        TargetRule("overdose history for family", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "overdose"}},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": "for", "OP": "?"},
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                   ]),
        TargetRule("family died suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "(commit(ted)?|died|death|kill(ed)?)"}},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),

        TargetRule("family had a history of suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "[^.].*"}, "OP": "?"},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "((h\/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("family with depression and suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "with"}, "OP": "?"},
                       {"LOWER": {"REGEX": "(depression)"}},
                       {"LOWER": {"REGEX": "(and|or)"}, "OP": "?"},
                       {"LOWER": {"REGEX": "[\d]"}, "OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("family history of psychiatric illness or suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "((h/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": {"REGEX": "of"}, "OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("father an alcohol and died by suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "(alcohol(ic)?)"}},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "(commit(ted)?|died|dead|death|kill(ed)?)"}},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("Brother with death that may have been suicide", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "^[^.'\-\,].*"}},
                       {"LOWER": {"REGEX": "(commit(ted)?|died|dead|death|kill(ed)?)"}},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("Family history significant for depression and  suicidality", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"LOWER": {"REGEX": "((h/o)|hx|history|prev|previous|past|earlier|past|prior)"}},
                       {"LOWER": {"REGEX": "(significant)"}},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "suicid(e|al)(ity)?"}},
                   ]),
        TargetRule("family SA by hanging", "FAMILY SUICIDE HISTORY",
                   pattern=[
                       {"LOWER": {"REGEX": "(family|(((grand)?(father|mother|daughter|son)|brother|sister|aunt|uncle|cousin|nephew|niece)))"}},
                       {"OP": "?"},
                       {"LOWER": {"REGEX": "(commit(ted)?|completed|(un)?successful|died|\bSA\b|death|kill(ed)?)"}},
                       {"LOWER": {"REGEX": "(of|by|from)"}, "OP": "?"},
                       {"LOWER": {"REGEX": "(hanging|overdose)"}},
                   ]),
    ]